service: nest-test

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  memorySize: 2048
  stage: dev
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    ACCESS_TOKEN_EXPIRATION: ${env:ACCESS_TOKEN_EXPIRATION}
    
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
    REFRESH_TOKEN_EXPIRATION: ${env:REFRESH_TOKEN_EXPIRATION}

package:
  exclude:
    - src/**

functions:
  main:
    handler: dist/index.handler
    events:
    # Auth Routes
      - http:
          method: POST
          path: /auth/signup
      - http:
          method: POST
          path: /auth/signin
      - http:
          method: GET
          path: /auth/access
      - http:
          method: GET
          path: /auth/logout
    # User Routes
      - http:
          method: GET
          path: /user/{id}
      - http:
          method: PATCH
          path: /user/{id}
      - http:
          method: DELETE
          path: /user/{id}
    # Order Routes
      - http:
          method: POST
          path: /order
      - http:
          method: PATCH
          path: /order/pay/{id}
      - http:
          method: GET
          path: /order/paid
    # Cart Routes
      - http:
          method: POST
          path: /cart
      - http:
          method: GET
          path: /cart/current
      - http:
          method: PATCH
          path: /cart/{id}
    # Product Routes
      - http:
          method: POST
          path: /product
      - http:
          method: GET
          path: /product
      - http:
          method: GET
          path: /product/{id}
      - http:
          method: PATCH
          path: /product/{id}
      - http:
          method: DELETE
          path: /product/{id}